# -*- coding: utf-8 -*-
"""System_and_Signals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ES0eymV4JD3DAUfr_DfmfDu7AsfdfUP2

Cuda Pacakges installation
"""

!pip install pycuda
!curl https://colab.chainer.org/install | sh -
!sudo apt-get install nvidia-modprobe

"""Import cuda stuff for python"""

import pycuda.driver as cuda 
import pycuda.autoinit
from pycuda.compiler import SourceModule
# Import numpy and random in order to handle arrays
import numpy as np
import random
# To handle .wav files
from scipy.io.wavfile import read
import scipy.io.wavfile as wavOut

"""Convolution function """

def MyConvolve(A, B):
 
  # Allocate space for the arrays on the GPU
  a_cuda = cuda.mem_alloc(A.nbytes)
  b_cuda = cuda.mem_alloc(B.nbytes)
  c_cuda = cuda.mem_alloc(A.nbytes)

  C = np.empty_like(A)

  # copy data from cpu (host) to gpu (device) allocated space
  cuda.memcpy_htod(a_cuda, A)
  cuda.memcpy_htod(b_cuda, B)
  cuda.memcpy_htod(c_cuda, C)


  # GPU kenrel code - convolution implementation
  convCudaScript = SourceModule("""
  __global__ void conv1d(float *A, float *B, int lenA, int lenB, float *C){

    // thread index
    int tIndex = blockIdx.x * blockDim.x + threadIdx.x;

    //  number of elements left or right of the middle element of B array (mask)
    int r = int(lenA/2);

    // begin from
    int strt =  tIndex - r;

    float sumOfMults = 0.f;

    // loop over the elements of array B
    for (int i = 0; i < lenB; i++) {
      // throw outrange elements
      if ((strt + i >= 0) && (strt + i < lenA)) {
      sumOfMults += (A[strt + i] * B[i]);
      }
    }

    C[tIndex] = sumOfMults;
  } 
  """)

  # calculate blocks 
  threads = 256;
  lenA = len(A)
  lenB = len(B)
  blocks = int((len(A) + threads - 1) / threads)
  kernelFunction = convCudaScript.get_function("conv1d")
  kernelFunction(a_cuda, b_cuda, np.int32(lenA), np.int32(lenB), c_cuda, block=(blocks, 1, 1), grid=(1, 1, 1))

  
  cuda.memcpy_dtoh(C, c_cuda)

  return C

"""PART A"""

# array A with N random 32 bit floats
a = []
N = int(input("N : "))

for i in range(N):
  a.append(random.uniform(0.0, 500.0))

A = np.array(a)
A = A.astype(np.float32)

b = [1/5, 1/5, 1/5, 1/5, 1/5]
B = np.array(b)
B = B.astype(np.float32)

C = MyConvolve(A, B)

print(C)

"""PART B"""

# Pink noise

# Read wav files
SampleAudio = read("/content/drive/MyDrive/signal - systems/sample_audio.wav")
PinkNoise = read("/content/drive/MyDrive/signal - systems/pink_noise.wav")

# transform to arrays
SampleAudioAr = np.array(SampleAudio[1],dtype=float)
PinkNoiseAr = np.array(PinkNoise[1],dtype=float)

#SampleAudioAr = np.asarray(SampleAudio[1])
#PinkNoiseAr = np.asarray(PinkNoise[1])


SampleAudioAr = SampleAudioAr.astype(np.float32)
PinkNoiseAr = PinkNoiseAr.astype(np.float32)


#PinkNoiseAr = PinkNoiseAr * 0.3

rarray = MyConvolve(SampleAudioAr, PinkNoiseAr)


result = "/content/drive/MyDrive/signal - systems/pinkNoise_sampleAudio2.wav"
#wavOut.write(result, SampleAudio[0], rarray)

# WhiteNoise signal --> with can use radnom values ( Spectrum should contain every frequency )

WhiteNoise =  np.random.random_sample((132300,))

WhiteNoise = WhiteNoise.astype(np.float32)

rarray2 = MyConvolve(SampleAudioAr, WhiteNoise)

result2 = "/content/drive/MyDrive/signal - systems/whiteNoise_sampleAudio.wav"

wavOut.write(result2, SampleAudio[0], rarray2)
